services:
  TuiMusement\CityWeather\Infrastructure\MusementAPI:
    class: TuiMusement\Test\Stub\MusementAPIStub
  TuiMusement\CityWeather\Infrastructure\WeatherAPI:
    class: TuiMusement\Test\Stub\WeatherAPIStub
