services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TuiMusement\Application:
    public: true
    arguments:
      $commands: !tagged console.command
      $name: '%app_name%'
      $version: '%app_version%'

  TuiMusement\App\Command\CityWeatherListCommand:
    tags:
      - { name: 'console.command', command: 'list:cities' }

  TuiMusement\CityWeather\Application\CityWeatherFacade: ~

  TuiMusement\CityWeather\Model\CityRepository:
    class: TuiMusement\CityWeather\Infrastructure\Repository\HttpCityRepository
  TuiMusement\CityWeather\Model\WeatherRepository:
    class: TuiMusement\CityWeather\Infrastructure\Repository\HttpWeatherRepository

  TuiMusement\CityWeather\Infrastructure\Repository\CityFactory: ~
  TuiMusement\CityWeather\Infrastructure\Repository\WeatherFactory: ~

  Psr\Http\Client\ClientInterface:
    class: Symfony\Component\HttpClient\Psr18Client

  Psr\Http\Message\RequestFactoryInterface:
    class: Symfony\Component\HttpClient\Psr18Client

  Psr\Http\Message\UriFactoryInterface:
    class: Symfony\Component\HttpClient\Psr18Client

  TuiMusement\CityWeather\Infrastructure\MusementAPI:
    class: TuiMusement\CityWeather\Infrastructure\Service\MusementAPIClient
    arguments:
      $musementApiUri: '%musement_api_url%'
  TuiMusement\CityWeather\Infrastructure\WeatherAPI:
    class: TuiMusement\CityWeather\Infrastructure\Service\WeatherAPIClient
    arguments:
      $weatherApiUrl: '%weather_api_url%'
      $weatherApiKey: '%weather_api_key%'
