services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TuiMusement\Application:
    public: true
    arguments:
      $commands: !tagged console.command
      $name: '%app_name%'
      $version: '%app_version%'

  TuiMusement\CityWeather\Application\CityWeatherListCommand:
    tags:
      - { name: 'console.command', command: 'list:cities' }

  TuiMusement\CityWeather\Application\CityWeatherFacade: ~

  TuiMusement\CityWeather\Model\CityRepository:
    class: TuiMusement\CityWeather\Infrastructure\Repository\InMemoryCityRepository
  TuiMusement\CityWeather\Model\WeatherRepository:
    class: TuiMusement\CityWeather\Infrastructure\Repository\InMemoryWeatherRepository
