services:
  TuiMusement\CityWeather\Infrastructure\MusementAPI:
    class: TuiMusement\Test\CityWeather\Fake\MusementAPIFake
  TuiMusement\CityWeather\Infrastructure\WeatherAPI:
    class: TuiMusement\Test\CityWeather\Fake\WeatherAPIFake
